run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Bugs
    - errcheck      # Check error returns
    - gosec         # Security issues
    - staticcheck   # Static analysis
    - govet         # Go vet checks

    # Style
    - gofmt         # Formatting
    - goimports     # Import organization
    - misspell      # Spelling mistakes
    - revive        # Replacement for golint

    # Complexity
    - gocyclo       # Cyclomatic complexity
    - funlen        # Function length

    # Performance
    - prealloc      # Suggest preallocations

linters-settings:
  funlen:
    lines: 100      # Warn on functions over 100 lines
    statements: 50

  gocyclo:
    min-complexity: 15  # Warn on complex functions

  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    # Ignore long lines in generated files
    - path: "_test\\.go"
      linters:
        - funlen