package middleware

import (
	"crypto/sha256"
	"encoding/hex"
	"net/http"
	"os"
	"time"

	"github.com/ndewijer/Investment-Portfolio-Manager-Backend/internal/api/response"
)

// APIKeyMiddleware validates requests using dual-factor authentication:
// 1. X-API-Key header must match INTERNAL_API_KEY environment variable
// 2. X-Time-Token header must contain a valid time-based token (valid for current hour)
// The time token is generated by hashing the API key with the current hour in UTC.
// This provides replay protection and ensures tokens expire hourly.
func APIKeyMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		validAPIKey := os.Getenv("INTERNAL_API_KEY")
		if validAPIKey == "" {
			response.RespondError(w, http.StatusInternalServerError, "Unauthorized", "Authentication not loaded")
			return
		}

		apiKey := r.Header.Get("X-API-Key")
		if apiKey == "" {
			response.RespondError(w, http.StatusUnauthorized, "Unauthorized", "Missing API key")
			return
		}
		if apiKey != validAPIKey {
			response.RespondError(w, http.StatusUnauthorized, "Unauthorized", "Invalid API key")
			return
		}

		timeToken := GenerateTimeToken(validAPIKey)

		providedToken := r.Header.Get("X-Time-Token")
		if providedToken == "" {
			response.RespondError(w, http.StatusUnauthorized, "Invalid token", "Missing Time token")
			return
		}
		if providedToken != timeToken {
			response.RespondError(w, http.StatusUnauthorized, "Invalid token", "Time token is invalid or expired")
			return
		}

		next.ServeHTTP(w, r)
	})
}

// GenerateTimeToken generates a time-based token for the current hour using SHA-256.
// The token is created by hashing the API key concatenated with the current hour (UTC format: 2006-01-02-15).
// This function can be used for testing or generating tokens programmatically.
// Tokens are valid only for the hour in which they were generated.
func GenerateTimeToken(apiKey string) string {
	currentHour := time.Now().UTC().Format("2006-01-02-15")
	hash := sha256.New()
	hash.Write([]byte(apiKey + currentHour))
	return hex.EncodeToString(hash.Sum(nil))
}
